CREATE TABLE `sap-supplier-invoice-account-assignment-data`
(
    `SupplierInvoice`         varchar(10) NOT NULL,
    `FiscalYear`              varchar(4) NOT NULL,
    `SupplierInvoiceItem`     varchar(6) NOT NULL,
    `CompanyCode`             varchar(4) DEFAULT NULL,
    `CostCenter`              varchar(10) DEFAULT NULL,
    `ControllingArea`         varchar(4) DEFAULT NULL,
    `BusinessArea`            varchar(4) DEFAULT NULL,
    `ProfitCenter`            varchar(10) DEFAULT NULL,
    `FunctionalArea`          varchar(16) DEFAULT NULL,
    `GLAccount`               varchar(10) DEFAULT NULL,
    `SalesOrder`              varchar(10) DEFAULT NULL,
    `SalesOrderItem`          varchar(6) DEFAULT NULL,
    `CostObject`              varchar(12) DEFAULT NULL,
    `WBSElement`              varchar(8) DEFAULT NULL,
    `DocumentCurrency`        varchar(5) DEFAULT NULL,
    `SuplrInvcAcctAssignmentAmount` varchar(13) DEFAULT NULL,
    `TaxCode`                 varchar(2) DEFAULT NULL,
    `WorkItem`                varchar(10) DEFAULT NULL,
    `MasterFixedAsset`        varchar(12) DEFAULT NULL,
    `FixedAsset`              varchar(4) DEFAULT NULL,
    `DebitCreditCode`         varchar(1) DEFAULT NULL,
    `InternalOrder`           varchar(12) DEFAULT NULL,
    `ProjectNetwork`          varchar(10) DEFAULT NULL,
    `ProfitabilitySegment`    varchar(10) DEFAULT NULL,
    PRIMARY KEY (`SupplierInvoice`, `FiscalYear`, `SupplierInvoiceItem`),
    CONSTRAINT (`SupplierInvoice_fk`, `FiscalYear_fk`) FOREIGN KEY (`SupplierInvoice`, `FiscalYear`) REFERENCES `sap-supplier-invoice-header-data` (`SupplierInvoice`, `FiscalYear`)
) ENGINE = InnoDB
  DEFAULT CHARSET = utf8mb4;
